CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  whatsapp_id TEXT UNIQUE NOT NULL,
  is_logged_in BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
