// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type User struct {
	ID         int32
	WhatsappID string
	IsLoggedIn bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
