// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID           int32
	WhatsappID   string
	AccessToken  sql.NullString
	RefreshToken sql.NullString
	TokenExpiry  sql.NullTime
	IsLoggedIn   bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
